services:
  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN:-}
      ADMIN_ID: ${ADMIN_ID:-}
    depends_on:
      - redis
    command: ["python", "bot.py"]

  redis:
    image: redis:latest
    expose:
      - "6379"
